<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tamerlan-ThinkPad" failures="1" tests="1" name="titleTest" time="7.809" errors="0" timestamp="2020-07-21T16:27:36 EDT">
  <testcase classname="project.validateTitleTest" name="home" time="0.035">
    <failure type="java.lang.AssertionError" message="expected [Responding toto the Coronavirus] but found [Responding to the Coronavirus]">
      <![CDATA[java.lang.AssertionError: expected [Responding toto the Coronavirus] but found [Responding to the Coronavirus]
at project.validateTitleTest.home(validateTitleTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- home -->
</testsuite> <!-- titleTest -->
